server:
  port: 19041

spring:
  application:
    name: paymentservice

  config:
    import:
      - optional:configserver:http://localhost:8888
      - optional:classpath:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${PAYMENT_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org.flywaydb: info
    com.pagely.paymentservice: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    enabled: false
    register-with-eureka: false
    fetch-registry: false

toss:
  base-url: ${TOSS_API_BASE_URL}
  secret-key: ${TOSS_SECRET_KEY}
